#!/bin/bash

set -euo pipefail

export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

if [ -z "${PDINFO:-}" ]; then
    exit 0
fi

echo "$PDINFO"

# Alpine doesn't have ipv6calc.
mac_to_eui64() {
    IFS=: read -r a b c d e f <<< "$1"
    printf "%02x%02x:%02xff:fe%02x:%02x%02x" \
        "$((0x$a ^ 2))" "0x$b" "0x$c" "0x$d" "0x$e" "0x$f"
}

prefix=$(echo "$PDINFO" | cut -d' ' -f1)
prefix_public=$(ipcalc -j -S 64 "$prefix" | jq -r '.SPLITNETWORK[10]')

prefix_lan_inet_hs=$(ipcalc -j -S 64 "$prefix" | jq -r '.SPLITNETWORK[45]')
addr_cloudflare_data="${prefix_lan_inet_hs::-5}:$(mac_to_eui64 8e:cc:7e:8a:4e:16)"

nft flush set inet router cloudflare_data
nft add element inet router cloudflare_data "{ $addr_cloudflare_data }"

echo -n "$addr_cloudflare_data" > /run/dhcp6c-addresses/addr_cloudflare_data

nft -f - <<EOF
flush chain inet router translate_wg0_prefix
table inet router {
    chain translate_wg0_prefix {
        ip6 saddr fd33:1491:4cfa:1000::/64 snat ip6 prefix to $prefix_public
    }
}
EOF
