---

# Network connections
- name: "Connection: Bridge"
  ansible.builtin.copy:
    src: files/etc/NetworkManager/system-connections/bridge-br0.nmconnection
    dest: /etc/NetworkManager/system-connections/bridge-br0.nmconnection
    mode: '0600'

- name: "Connection: LAN"
  ansible.builtin.copy:
    src: files/etc/NetworkManager/system-connections/bridge-slave-enp1s0.nmconnection
    dest: /etc/NetworkManager/system-connections/bridge-slave-enp1s0.nmconnection
    mode: '0600'

- name: "Connection: LAN Management"
  ansible.builtin.copy:
    src: files/etc/NetworkManager/system-connections/lan_mgmt.nmconnection
    dest: /etc/NetworkManager/system-connections/lan_mgmt.nmconnection
    mode: '0600'

- name: "Connection: LAN Guest"
  ansible.builtin.copy:
    src: files/etc/NetworkManager/system-connections/lan_guest.nmconnection
    dest: /etc/NetworkManager/system-connections/lan_guest.nmconnection
    mode: '0600'

- name: "Connection: Modem"
  ansible.builtin.copy:
    src: files/etc/NetworkManager/system-connections/modem.nmconnection
    dest: /etc/NetworkManager/system-connections/modem.nmconnection
    mode: '0600'

- name: "Connection: WAN"
  ansible.builtin.template:
    src: files/etc/NetworkManager/system-connections/wan.nmconnection
    dest: /etc/NetworkManager/system-connections/wan.nmconnection
    mode: '0600'
  tags: needs_secrets

- name: "Connection: Wireguard main"
  ansible.builtin.template:
    src: "{{ secrets_dir }}/wg_main.nmconnection"
    dest: /etc/NetworkManager/system-connections/wg_main.nmconnection
    mode: '0600'
  tags: needs_secrets

- name: "Connection: Wireguard parents"
  ansible.builtin.template:
    src: "{{ secrets_dir }}/wg_parents.nmconnection"
    dest: /etc/NetworkManager/system-connections/wg_parents.nmconnection
    mode: '0600'
  tags: needs_secrets

- name: "SQM: ppp0"
  ansible.builtin.copy:
    src: files/etc/sqm/ppp0.iface.conf
    dest: /etc/sqm/ppp0.iface.conf
    mode: '0644'

# Firewall
- name: "Firewall"
  ansible.builtin.copy:
    src: files/etc/sysconfig/nftables.conf
    dest: /etc/sysconfig/nftables.conf
    mode: '0644'

# sysctl
- name: "Sysctl"
  ansible.builtin.copy:
    src: files/etc/sysctl.d/30-router.conf
    dest: /etc/sysctl.d/30-router.conf
    mode: '0644'

# Containers
- name: "subuid"
  ansible.builtin.copy:
    dest: /etc/subuid
    owner: root
    group: root
    mode: '0644'
    content: |
      containers:100000:1000000000

- name: "subgid"
  ansible.builtin.copy:
    dest: /etc/subgid
    owner: root
    group: root
    mode: '0644'
    content: |
      containers:100000:1000000000

# secrets
- name: "dnsmasq hosts"
  ansible.builtin.template:
    src: "{{ secrets_dir }}/dnsmasq-hosts"
    dest: /usr/local/share/container-dnsmasq/hosts
    mode: '0644'
  tags: needs_secrets

- name: "Private dnsmasq config"
  ansible.builtin.template:
    src: "{{ secrets_dir }}/dnsmasq-private.conf"
    dest: /usr/local/share/container-dnsmasq/dnsmasq.d/private.conf
    mode: '0644'
  tags: needs_secrets

- name: "ddclient config"
  ansible.builtin.template:
    src: "{{ secrets_dir }}/ddclient.conf"
    dest: /usr/local/share/container-ddclient.conf
    mode: '0600'
  tags: needs_secrets

- name: "nftables variables"
  ansible.builtin.template:
    src: "{{ secrets_dir }}/nftables-vars-private.nft"
    dest: /usr/local/share/nftables-vars-private.nft
    mode: '0600'
  tags: needs_secrets
