---

# usrlocal
- name: "rsync: /usr/local/bin"
  ansible.posix.synchronize:
    src: files/usr/local/bin/
    dest: /usr/local/bin
    checksum: true
    delete: true
    recursive: true
    rsync_opts:
      - "--chown=root:root"

- name: "rsync: /usr/local/lib"
  ansible.posix.synchronize:
    src: files/usr/local/lib/
    dest: /usr/local/lib
    checksum: true
    delete: true
    recursive: true
    rsync_opts:
      - "--chown=root:root"

- name: "rsync: /usr/local/share"
  ansible.posix.synchronize:
    src: files/usr/local/share/
    dest: /usr/local/share
    checksum: true
    delete: true
    recursive: true
    rsync_opts:
      - "--chown=root:root"
      - "--exclude=container-dnsmasq/hosts"
      - "--exclude=container-dnsmasq/dnsmasq.d/private.conf"
      - "--exclude=container-ddclient.conf"

# containers
- name: "rsync: /etc/containers/systemd"
  ansible.posix.synchronize:
    src: files/etc/containers/systemd/
    dest: /etc/containers/systemd
    checksum: true
    delete: true
    recursive: true
    rsync_opts:
      - "--chown=root:root"
  notify: reload_systemd
