---
- name: "Service: nftables"
  ansible.builtin.systemd:
    name: nftables.service
    enabled: true
    state: started

- name: "Service: sqm@ppp0"
  ansible.builtin.systemd:
    name: sqm@ppp0.service
    enabled: true
    state: started

- name: "Service: podman-auto-update"
  ansible.builtin.systemd:
    name: podman-auto-update.timer
    enabled: true
    state: started

- name: "Timer: podman-auto-update"
  ansible.builtin.systemd:
    name: container-image-builder.timer
    enabled: true
    state: started
