#!/bin/sh

set -euo pipefail

# Source: https://stackoverflow.com/a/29613573
escape_sed_replacement() {
	echo -n "$1" | sed 's/[&/\]/\\&/g'
}

replace_template() {
	local template="$1"
	local replacement="$2"
	local file="$3"
	local replacement_escaped

	replacement_escaped=$(escape_sed_replacement "$replacement")

	sed -i "s/{{ $template }}/$replacement_escaped/g" "$file"
}

cp /run/media/config/config.yaml /opt/adguardhome/AdGuardHome.yaml
replace_template admin_password "$(cat /run/secrets/adguardhome_admin_password)" \
	/opt/adguardhome/AdGuardHome.yaml

exec /opt/adguardhome/AdGuardHome
